server:
  port: 9201
spring:
  profiles:
    active: prod
  application:
    name: micro-oauth2-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://119.91.200.72:8848

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*" # spring boot2.4配置
            # allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      routes: #配置路由规则
        - id: oauth2-teach-route
          uri: lb://micro-teaching-quality
          predicates:
            - Path=/teaching/**
          filters:
            - StripPrefix=1

        - id: oauth2-auth-route
          uri: lb://micro-oauth2-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  redis:
    database: 0
    port: 6379
    host: 119.91.200.72
    password: cph
  main:
    allow-bean-definition-overriding: true
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/**"